# Generated by Django 6.0.3 on 2026-04-06 03:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Nueva conversación', max_length=255)),
                ('summary', models.TextField(blank=True, default='', help_text='Resumen comprimido de los turnos anteriores para optimizar tokens.', verbose_name='Resumen del historial')),
                ('turn_count', models.PositiveIntegerField(default=0, verbose_name='Contador de turnos')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Conversación',
                'verbose_name_plural': 'Conversaciones',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'Usuario'), ('assistant', 'Asistente')], max_length=10)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.conversation')),
            ],
            options={
                'verbose_name': 'Mensaje',
                'verbose_name_plural': 'Mensajes',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_prompt', models.TextField(blank=True, default='', help_text='Describe cómo quieres que se comporte el asistente. Ej: "Eres un pirata divertido".', verbose_name='Prompt del sistema')),
                ('assistant_name', models.CharField(default='Asistente', max_length=100, verbose_name='Nombre del asistente')),
                ('avatar_emoji', models.CharField(default='🤖', max_length=10, verbose_name='Emoji del asistente')),
                ('n8n_webhook_url', models.CharField(blank=True, default='', help_text='Dejar vacío para usar el webhook global configurado en .env', max_length=500, verbose_name='URL webhook n8n personalizada')),
                ('n8n_workflow_id', models.CharField(blank=True, default='', max_length=100, verbose_name='ID workflow n8n')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de usuario',
                'verbose_name_plural': 'Perfiles de usuario',
            },
        ),
        migrations.CreateModel(
            name='UserFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(default='otro', help_text='Ej: amigo, color_favorito, tema, mascota', max_length=50, verbose_name='Categoría')),
                ('key', models.CharField(help_text='Ej: "Mejor amigo", "Color favorito"', max_length=100, verbose_name='Qué recordar')),
                ('value', models.CharField(help_text='Ej: "Carlos", "azul"', max_length=255, verbose_name='Valor')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Hecho del usuario',
                'verbose_name_plural': 'Hechos del usuario',
                'ordering': ['category', 'key'],
                'unique_together': {('user', 'key')},
            },
        ),
    ]
