# Generated by Django 6.0.3 on 2026-04-07 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_userprofile_sex_birthdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='prompt_comportamiento',
            field=models.TextField(blank=True, default='', help_text='Qué debe y no debe hacer. Tono, límites, prioridades.', verbose_name='Comportamiento'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='prompt_contexto',
            field=models.TextField(blank=True, default='', help_text='Para qué existe, en qué plataforma o empresa.', verbose_name='Contexto'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='prompt_formato',
            field=models.TextField(blank=True, default='', help_text='Largo, idioma, markdown sí/no, estructura de respuestas.', verbose_name='Formato de respuesta'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='prompt_restricciones',
            field=models.TextField(blank=True, default='', help_text='Lo que nunca debe hacer, temas fuera de scope.', verbose_name='Restricciones'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='prompt_rol',
            field=models.TextField(blank=True, default='', help_text='Quién es el asistente: identidad, expertise, personalidad.', verbose_name='Rol'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='use_structured_prompt',
            field=models.BooleanField(default=False, verbose_name='Usar prompt estructurado'),
        ),
    ]
