# Generated by Django 6.0.3 on 2026-04-07 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_promptprofile_remove_userprofile_prompts'),
    ]

    operations = [
        migrations.AddField(
            model_name='promptprofile',
            name='comportamiento_label',
            field=models.CharField(default='COMPORTAMIENTO', max_length=50),
        ),
        migrations.AddField(
            model_name='promptprofile',
            name='contexto_label',
            field=models.CharField(default='CONTEXTO', max_length=50),
        ),
        migrations.AddField(
            model_name='promptprofile',
            name='formato_label',
            field=models.CharField(default='FORMATO', max_length=50),
        ),
        migrations.AddField(
            model_name='promptprofile',
            name='restricciones_label',
            field=models.CharField(default='RESTRICCIONES', max_length=50),
        ),
        migrations.AddField(
            model_name='promptprofile',
            name='rol_label',
            field=models.CharField(default='ROL', max_length=50),
        ),
        migrations.AlterField(
            model_name='promptprofile',
            name='prompt_comportamiento',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='promptprofile',
            name='prompt_contexto',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='promptprofile',
            name='prompt_formato',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='promptprofile',
            name='prompt_restricciones',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='promptprofile',
            name='prompt_rol',
            field=models.TextField(blank=True, default=''),
        ),
    ]
