# Generated by Django 6.0.3 on 2026-04-07 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_promptprofile_labels'),
    ]

    operations = [
        migrations.AddField(
            model_name='promptprofile',
            name='excepciones_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='promptprofile',
            name='excepciones_label',
            field=models.CharField(default='EXCEPCIONES', max_length=50),
        ),
        migrations.AddField(
            model_name='promptprofile',
            name='prompt_excepciones',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='promptprofile',
            name='comportamiento_label',
            field=models.CharField(default='OBJETIVO', max_length=50),
        ),
        migrations.AlterField(
            model_name='promptprofile',
            name='formato_label',
            field=models.CharField(default='ESTILO', max_length=50),
        ),
        migrations.AlterField(
            model_name='promptprofile',
            name='restricciones_label',
            field=models.CharField(default='REGLAS', max_length=50),
        ),
    ]
